#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
   0x3625E953, // 233.83
   0x894A28C4, // 40.196
   0x90D90481, // 4.129
   0xB9F135E4, // 53.228
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
